management:
  endpoints:
    web:
      exposure:
        include: "env, health, info, loggers"
  endpoint:
    refresh:
      enabled: true
    beans:
      enabled: true

server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://github.com/lswteen/spring-cloud-config-sample

